export default {
	loadingOnlyText: false,
	emptyOnlyText: false,
	finishedOnlyText: true,
	errorOnlyText: false,
	loadMoreOnlyText: true,
	loadingText: '正在加载中...',
	emptyText: '未找到结果，换个姿势再来~',
	finishedText: '没有更多数据啦',
	errorText: '网络君被堵在二环高架上了~',
	loadMoreText: '点击或上拉加载更多',
	errorBtnText: '重新加载',
	loadmoreBtnText: '加载更多',
	loadingIcon: 'tips-icon-loading',
	emptyIcon: 'tips-icon-empty',
	finishedIcon: 'tips-icon-finished',
	errorIcon: 'tips-icon-error',
	loadmoreIcon: 'tips-icon-loadmore',
}
